# .gitlab-ci.yml — exact mirror of upstream to GitHub / GitLab.com / Codeberg
stages: [deploy]

mirror:all-refs:
  stage: deploy
  image: alpine:3.22
  variables:
    GIT_STRATEGY: fetch
    GIT_DEPTH: "0"
  rules:
    # run for main branch updates and for tag pipelines
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_TAG'
  script:
    - apk add --no-cache git
    - git config --global user.email "mirror@nullusionist.dev"
    - git config --global user.name  "Nova Mirror Bot"
    - git config --global safe.directory "$CI_PROJECT_DIR"

    # add remotes fresh each run
    - git remote remove github  2>/dev/null || true
    - git remote remove gitlab  2>/dev/null || true
    - git remote remove codeberg 2>/dev/null || true
    - git remote add github  "https://${MIRROR_GITHUB_TOKEN}@github.com/nullusionist/nova-tor-relay.git"
    - git remote add gitlab  "https://oauth2:${MIRROR_GITLAB_TOKEN}@gitlab.com/nullusionist/nova-tor-relay.git"
    - git remote add codeberg "https://${MIRROR_CODEBERG_TOKEN}@codeberg.org/nullusionist/nova-tor-relay.git"

    # make local match upstream (source of truth)
    - git fetch origin --prune --tags

    # mirror ALL refs (branches, tags, deletions, rewrites) to each remote
    - echo "==> Mirroring to GitHub";  git push --mirror github
    - echo "==> Mirroring to GitLab";  git push --mirror gitlab
    - echo "==> Mirroring to Codeberg";git push --mirror codeberg
