stages: [deploy]

.variables-template: &vars
  GIT_STRATEGY: fetch
  GIT_DEPTH: "0"

# Push main (after history rewrite) to mirrors, lease-protected.
mirror:branch:
  stage: deploy
  image: alpine:3.22
  variables: *vars
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - apk add --no-cache git
    - git config --global user.email "mirror@nullusionist.dev"
    - git config --global user.name "Nova Mirror Bot"
    - git config --global safe.directory "$CI_PROJECT_DIR"

    # remotes (tokens are project CI/CD variables)
    - git remote add github  "https://${MIRROR_GITHUB_TOKEN}@github.com/nullusionist/nova-tor-relay.git"
    - git remote add gitlab  "https://oauth2:${MIRROR_GITLAB_TOKEN}@gitlab.com/nullusionist/nova-tor-relay.git"
    - git remote add codeberg "https://${MIRROR_CODEBERG_TOKEN}@codeberg.org/nullusionist/nova-tor-relay.git"

    # make local 'main' exactly equal to origin/main
    - git fetch --all --tags
    - git checkout -B main origin/main

    # decide if we allow overwrite (default=1)
    - FORCE_FLAG=""; [ "${ALLOW_MIRROR_REWRITE:-1}" = "1" ] && FORCE_FLAG="--force-with-lease"

    # push main to all mirrors, pruning remote deleted refs
    - git push $FORCE_FLAG --prune github  main:main
    - git push $FORCE_FLAG --prune codeberg main:main
    - git push $FORCE_FLAG --prune gitlab  main:main

    # push tags (non-force is fine; they should only move forward)
    - git push github  --tags
    - git push codeberg --tags
    - git push gitlab  --tags --prune

# Tag-only pipeline: mirror just the tag, don’t touch branches.
mirror:tag:
  stage: deploy
  image: alpine:3.22
  variables: *vars
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - apk add --no-cache git
    - git config --global user.email "mirror@nullusionist.dev"
    - git config --global user.name "Nova Mirror Bot"
    - git config --global safe.directory "$CI_PROJECT_DIR"

    - git remote add github  "https://${MIRROR_GITHUB_TOKEN}@github.com/nullusionist/nova-tor-relay.git"
    - git remote add gitlab  "https://oauth2:${MIRROR_GITLAB_TOKEN}@gitlab.com/nullusionist/nova-tor-relay.git"
    - git remote add codeberg "https://${MIRROR_CODEBERG_TOKEN}@codeberg.org/nullusionist/nova-tor-relay.git"

    - git fetch --all --tags

    # push only the tag that triggered the pipeline
    - git push github  "$CI_COMMIT_TAG"
    - git push codeberg "$CI_COMMIT_TAG"
    - git push gitlab  "$CI_COMMIT_TAG"
