mirror:
  stage: deploy
  image: alpine:latest
  script:
    - apk add --no-cache git
    - git config --global user.email "mirror@nullusionist.dev"
    - git config --global user.name "Nova Mirror Bot"
    - git remote add github https://${MIRROR_GITHUB_TOKEN}@github.com/nullusionist/nova-tor-relay.git
    - git remote add gitlab https://oauth2:${MIRROR_GITLAB_TOKEN}@gitlab.com/nullusionist/nova-tor-relay.git
    - git remote add codeberg https://${MIRROR_CODEBERG_TOKEN}@codeberg.org/nullusionist/nova-tor-relay.git
    - git branch -f main origin/main
    - git push github --mirror
    - git push gitlab --mirror
    - git push codeberg --mirror
  only:
    - main
