services:
  relay:
    image: nullusionist/nova-tor-relay:latest
    container_name: nova-relay
    ports:
      - "9001:9001"   # ORPort
      - "9030:9030"   # DirPort
      - "9051:9051"   # ControlPort
    volumes:
      - tor-data:/var/lib/tor
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      CONTACT: ${CONTACT}
      BANDWIDTH_LIMIT: ${BANDWIDTH_LIMIT:-100 KB}
      BANDWIDTH_BURST: ${BANDWIDTH_BURST:-200 KB}
      NICKNAME: ${NICKNAME:-}
      OR_PORT: ${OR_PORT:-9001}
      DIR_PORT: ${DIR_PORT:-9030}
      CONTROL_PORT: ${CONTROL_PORT:-}
      EXIT_RELAY: ${EXIT_RELAY:-0}
      EXIT_POLICY: ${EXIT_POLICY:-}
      ACCOUNTING_START: ${ACCOUNTING_START:-}
      ACCOUNTING_MAX: ${ACCOUNTING_MAX:-}
      TOR_EXTRA_LINES: ${TOR_EXTRA_LINES:-}

# Optional self-updating Watchtower for automatic updates
#  watchtower:
#    image: containrrr/watchtower
#    container_name: watchtower
#    restart: unless-stopped
#    labels:
#      - "com.centurylinklabs.watchtower.enable=true"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    command: --label-enable --cleanup --interval 300

volumes:
  tor-data:
